### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by UlrichHoltzach** [OpenMusicKontrollers/synthpod#1]
Hi,
I really want to try this out, but I keep getting this one:

synthpod_jack: error while loading shared libraries: libsynthpod.so.0: cannot open shared object file: No such file or directory

I manually created $HOME/.local/share/synthpod, and everything seems to have been installed correctly.

Thanks !

**Comment by ventosus** [comment]
Great, testers are always welcome...

have you updated your library cache after installation?

    ldconfig /usr/lib
or
    ldconfig /usr/local/lib

**Comment by UlrichHoltzach** [comment]
It did the trick. I'll try it now ;)
