### ISSUE TITLE
Qt5 UI fails to build

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/synthpod#10]
Qt-5.7.1 on FreeBSD

```
In file included from bin/synthpod_sandbox_qt.cpp:187:
bin/synthpod_sandbox_qt5_moc.h:21:1: error: unknown type name 'QT_WARNING_DISABLE_DEPRECATED'
QT_WARNING_DISABLE_DEPRECATED
^
bin/synthpod_sandbox_qt5_moc.h:22:1: error: expected unqualified-id
struct qt_meta_stringdata_MyWindow_t {
^
bin/synthpod_sandbox_qt5_moc.h:31:14: error: unknown type name 'qt_meta_stringdata_MyWindow_t'
static const qt_meta_stringdata_MyWindow_t qt_meta_stringdata_MyWindow = {
             ^
bin/synthpod_sandbox_qt5_moc.h:33:1: error: unknown type name 'qt_meta_stringdata_MyWindow_t'
QT_MOC_LITERAL(0, 0, 8) // "MyWindow"
^
bin/synthpod_sandbox_qt5_moc.h:28:23: note: expanded from macro 'QT_MOC_LITERAL'
    qptrdiff(offsetof(qt_meta_stringdata_MyWindow_t, stringdata0) + ofs \
                      ^
```

**Comment by ventosus** [comment]
Well, this isn't a surprise, as I don't use any Qt plugins...

**Comment by yurivict** [comment]
I created the FreeBSD port for synthpod, rebuilt all UI executables, and found that this one isn't building. Had to label it broken for this reason.

**Comment by ventosus** [comment]
Cool, just keep in mind, this is early pre alpha, expect bugs, crashes, etc :)

**Comment by ventosus** [comment]
Easy fix for now: recreate the Qt moc file manually and then recompile. Will need to streamline this into the cmake build recipe...

    cd synthpod/bin
    moc synthpod_sandbox_qt.cpp > synthpod_sandbox_qt5_moc.h

**Comment by sergeybelobrov** [comment]
just delete the line QT_WARNING_DISABLE_DEPRECATED
And solved

**Comment by ventosus** [comment]
The proper fix will be to create moc files as part of the build process.
cmake can do this automagically, but it fails miserably at doing so in this case here, because we have both a Qt4 and Q5 project in the same project, which obviously interfere...

**Comment by ventosus** [comment]
As I've migrated from cmake to meson, this is fixed.
