### ISSUE TITLE
xcb-util-wm dependency should be only set for BUILD_SANDBOX_X11, not for all UIs

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/synthpod#11]

**Comment by ventosus** [comment]
xcb *is* only explicitely required for the x11 sandbox, why do you think it is needded for the other sandboxes, too?

https://github.com/OpenMusicKontrollers/synthpod/blob/master/bin/CMakeLists.txt#L186

**Comment by yurivict** [comment]
You are right. I go confused somehow. Sorry!
