### ISSUE TITLE
[suggestion] Configurable sound converter as a module?

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/synthpod#16]
I have the idea to create a sound conversion feature as a plugin for the instant messenger qTox (https://github.com/qTox/qTox). qTox is a secure messenger. Users can potentially appreciate voice scrambling feature, but in general it would be great to be able to apply any LV2 plugins too.

I am thinking about using synthpod for this, but I am not sure how to do this exactly.

Here's what it should do:
1. User selects to configure the plugin. This opens synthpod window with one input on the left, and one output on the right. User arranges the topology, the filter kicks in and works, until user disables it.
2. When configuration window is closed, filter still works.
3. When configuration window is reopened, it shows the same topology.
4. Configuration should be transparently persistent across app restarts/reboots.

So, there should be at least 3 objects.
1. Filter object: it gets input packets, and sinks output packets.
2. Configuration data, preferably a string, that can be saved.
3. Configuration window: can be opened any time to see/change the topology.

Here is the class prototype that needs to be implemented:
```
class Configuration {
  Configuration(const string &strSerialized);
  string serialize();
  void applyChange(const ConfigChange &change);
};
class ConfigChange {
  // contains one individual change that needs to be applied in the filter, like "connect a and b" or "delete c"
};
class Filter {
  Filter(const Configuration &configuration);
  // accepts signals:
  void sendPacket(Packet *packet);
  void configurationChanged(const list<ConfigChange> &configChanges) {/*atomically applies the list of changes*/}
  // fires signals
  void sinkPacket(const Packet* packet);
};

class ConfigWindow {
  void show(const Configuration &configuration); // can be called any time
  void close();
  // fires signals
  void configurationChanged(const list<ConfigChange> &configChanges);
};

// signals connections:
App -> Filter (sendPacket)
Filter -> App (sinkPacket)
ConfigWindow -> Filter (configurationChanged)
```

So the workflow will look like this:
```
Configuration configuration(savedConfigString);
Filter filter(configuration);
// connect App -> Filter (sendPacket)
// connect Filter -> App (sinkPacket)
// App keeps sending packets, and keeps receiving packets
...
ConfigWindow window;
// connect ConfigWindow -> Filter (configurationChanged)
window.show(configuration);
window.close();
...
// finished
configuration.serialize(); // user saves this configuration string
```

I think, many applications can use such interface.
Is such interface implementable using synthpod?

**Comment by ventosus** [comment]
`Is such interface implementable using synthpod?`

Synthpod has been designed as an application, it is therefore not straight-forward to use it as a library.

You basically want to add LV2 plugin support to qtox? Well then do it like all other LV2 hosts out there (including synthpod), by using liblilv [1] directly, which will take care of discovering/loading/saving LV2 plugins and their state (also arbitrary strings) and look at example clients [2].

[1] http://drobilla.net/software/lilv
[2] http://lv2plug.in/pages/developing.html

**Comment by yurivict** [comment]
> You basically want to add LV2 plugin support to qtox? Well then do it like all other LV2 hosts out there (including synthpod), by using liblilv [1] directly

liblilv doesn't have the UI. Synthpod has GUI, this is why I want to use it.

**Comment by ventosus** [comment]
qtox has a UI, most probably Qt? I'm pretty sure there are flow chart classes out there you could reuse. e.g. something like this [1]?

[1] http://adared.ch/qnodeseditor-qt-nodesports-based-data-processing-flow-editor/

**Comment by yurivict** [comment]
Ok, thanks, I will research Qt-based solutions.
