### ISSUE TITLE
How to I add plugins to the Synthpod graph?

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/synthpod#19]
I have run synthpod_nk and I have this:

![screenshot_20170825_191049](https://user-images.githubusercontent.com/491704/29724545-2393b070-89c9-11e7-836a-85405a15673e.png)

You can see x42-scope running that show I managed to copy L channel of input to L and R channels on output with Synthpod. Yeah!

I managed to figure out how to move nodes (by draggin them while holding Ctrl)
How to pan the area (with middle mouse button)
How to connect ports (by dragging between them)
And how to alter stereo channle routing with that grid node I got.

But that's it. How do I add new plugins to the graph?

I've been looking in manpages but I found nothing. Looks like there is no documentation for Synthpod yet. Or is it?

**Comment by ventosus** [comment]
Well, the UI and user interaction is a work-in-progress, so no documentation, yet, sorry.

But you got the basics, alright. Mouse bindings should be similar to patchmatrix [1], which it shares some code with.

A plugin is added by left-clicking on the plugin name in the plugin list.

* Left-clicking a plugin gives it focues (and shows controls, presets, automations)
* Right-clicking a node removes all its connections
* Right-clicking a plugin removes the plugin (and all its connections)
* Shift-right-clicking a plugin open its UI (if it has one)

[1] https://github.com/OpenMusicKontrollers/patchmatrix

**Comment by unfa** [comment]
Thanks! Hmm. Wierd. Clicking on the plugin list doens't seem to do anything on my side:

![screenshot_20170827_163143](https://user-images.githubusercontent.com/491704/29750728-38f1482e-8b45-11e7-92e1-fceb190cc7c6.png)

**Comment by ventosus** [comment]
Looking at the monospace font, this is not an up-to-date version of synthpod, so it's hard to tell who and when has compiled it.

Older versions (maybe yours?) needed click + enter key. Current version is happy with a single click.

**Comment by unfa** [comment]
I'll try building from latest source then and get back with feedback :) Thanks!
