### ISSUE TITLE
Cannot load Synthpod Stereo plugin

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/synthpod#22]
I built and installed newest Synthpod, however when I try loading the LV2 plugin into any host it fails.

Ardour says:
![selection_052](https://user-images.githubusercontent.com/491704/31584451-35d6d84e-b1af-11e7-8d7b-ad337c2108d3.png)

Carla says:
![selection_053](https://user-images.githubusercontent.com/491704/31584461-5842af02-b1af-11e7-89cb-9c537615b79f.png)

Ingen says:
![selection_054](https://user-images.githubusercontent.com/491704/31584464-74202d26-b1af-11e7-9222-7cf1c604e63f.png)

Other plugins from the bundle load fine, like Synthpod Keyboard.

**Comment by ventosus** [comment]
This is expected, running synthpod as a plugin is currently disabled.
Some things in the backend have to change until it is enabled again

**Comment by unfa** [comment]
Thanks, I can't wait to see it up again. I'm starting to explore the performance again and Synthpod would be a fantastic tool to have. I am able to run an older version on my laptop and I can add plugins and experiment a bit

**Comment by unfa** [comment]
This is no longer the case. I can load it fine in Ardour.

**Comment by ventosus** [comment]
So we can close this issue for now :-)
