### ISSUE TITLE
No input/output ports shown in the graph

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/synthpod#23]
When I run `synthpod_jack` or `synthpod_jack -g` I see a flood of warning messages like this:

`(DSP) [Warn]  JACK XRun`

Also - there are no system in/out ports visible in the graph space -maybe that's related?

![selection_055](https://user-images.githubusercontent.com/491704/31585057-f8197532-b1ba-11e7-9c26-a0e41ded267e.png)

The `synthpod_alsa -g` also doesn't show anything in the graph:
![selection_056](https://user-images.githubusercontent.com/491704/31585192-2358ebda-b1be-11e7-93c4-d45186b7edf8.png)

I am unable to add any plugin too. I tried clicking various things, but no go.

**Comment by ventosus** [comment]
Well, there seems to be no communication between DSP and UI.
Any other messages on the console?
