### ISSUE TITLE
Stream of debug messages breaks alternative UI

### ISSUE THREAD

**Issue by milkmiruku** [OpenMusicKontrollers/synthpod#25]
The new constant stream of debug messages to the temrinal that launched Moony is interfering with the alternative UI feature.

![moony-vim](https://user-images.githubusercontent.com/108225/37865525-9af33094-2f75-11e8-8272-ea16f9ede403.png)

**Comment by ventosus** [comment]
You have checked-out at an unlucky commit, e.g. the synthpod UI writing out loads of debug messages and thus slowing down everything else.

Choose a more recent commit, e.g. 307af11cc7df6c9284b0c77cb1669e6ec542a3ef
