### ISSUE TITLE
Please have meson options to enable each individual plugin type

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/synthpod#28]
For example, Qt4 is EOLed and discontinued for many, it should be easy to disable. Qt5/Gtk2/Gtk3/etc should be easy to disable too.

**Comment by ventosus** [comment]
Why exactly do you need a meson option for those ?

The plugin wrappers for Qt4/5, Gtk2/3 are optional in the first place (e.g. disabled by default) and only built if libraries/headers are present. Isn't this what you want ?

**Comment by yurivict** [comment]
I still have Qt4 and Gtk2 installed, but don't want them to be used by synthpod. Auto-detection isn't what is desired. There are also port options that need to be able to set which backends to use.

**Comment by ventosus** [comment]
fixed in 38afb1c99b333

to disable use:

    meson build -Duse-qt4=false
