### ISSUE TITLE
synthpod_jack doesn't run

### ISSUE THREAD

**Issue by yagojrocket** [OpenMusicKontrollers/synthpod#3]
I'm not used to compile source code, after a lot of problems somehow I did it but when I tried to open synthpod, it just not run, here is my terminal output: 

> yago@yago-pc:~$ synthpod_jack
> Synthpod 0.1.1
> Copyright (c) 2015-2016 Hanspeter Portner (dev@open-music-kontrollers.ch)
> Released under Artistic License 2.0 by Open Music Kontrollers
> CRI<12002>:elementary elm_win.c:2858 _win_constructor() Software X11 engine creation failed. Trying default.
> ERR<12002>:elementary elm_win.c:2994 _win_constructor() Cannot create window.
> ERR<12002>:eo lib/eo/eo.c:1217 eo_error_set_internal() Error with obj '0x83f58e8' at elm_win.c:2995
> ERR<12002>:eo lib/eo/eo.c:1107 eo_add_internal() in elm_win.c:2718, Object of class 'Elm_Win' - One of the object constructors have failed.
> ERR<12002>:eo lib/eo/eo_ptr_indirection.x:275 _eo_obj_pointer_get() obj_id (nil) is not pointing to a valid object. Maybe it has already been freed.
> ERR<12002>:ecore_system_upower modules/ecore/system/upower/ecore_system_upower.c:74 _on_low_battery_get_cb() Message error org.freedesktop.DBus.Error.InvalidArgs - No such property OnLowBattery
> ERR<12002>:ecore lib/ecore/ecore.c:733 _ecore_magic_fail() 
> **\* ECORE ERROR: Ecore Magic Check Failed!!!
> **\* IN FUNCTION: ecore_con_server_send()
> ERR<12002>:ecore lib/ecore/ecore.c:735 _ecore_magic_fail()   Input handle pointer is NULL!
> ERR<12002>:ecore lib/ecore/ecore.c:746 _ecore_magic_fail() **\* NAUGHTY PROGRAMMER!!!
> **\* SPANK SPANK SPANK!!!
> **\* Now go fix your code. Tut tut tut!

**Comment by ventosus** [comment]
hi, thankgs for trying out sythpod

You most probably are on a debianesque distro and missing the X11 and/or OpenGL evas engines. 
I have not yet found an easy way to test for this at compile time, sorry.

Try this:
    sudo apt-get install libevas1-engines-x

**Comment by ventosus** [comment]
since commit e30ea1a, cmake should now warn about absent evas X11 engines while configuraing the build environment.

**Comment by yagojrocket** [comment]
Great, well, I got some broken packages and I am not able to deal with my messed up configuration haha
Plus I installed elementary and efl from source code and now I see that exists an ppa for that, well, I will reinstall my system and do the things in the right way with a fresh install.

Yeah, I'm running Ubuntu because is very easy to import the KXStudio tools, and I have a atom netbook, so I need a very responsive configuration (I'm even using openbox), well, which distro would you recommend me?

**Comment by ventosus** [comment]
There's nothing wrong with Debian/Ubuntu. Contiuous integration for synthpod is running on an Ubuntu Trusty image on travis. You may want to have a look at the travis recipe to figure out what packages/PPAs are being installed on the virtual image:

https://github.com/OpenMusicKontrollers/synthpod/blob/master/.travis.yml

> which distro would you recommend me?

I know better to recommend any distro to anybody ;-) a matter of taste, really. I use ArchLinux and am happy with it.

**Comment by yagojrocket** [comment]
Omg, I would have avoided a headache if I had seen this recipe before lol :sweat_smile: 

Never mind, I'm frequently testing distros and tips are always welcome :stuck_out_tongue: 

I really like the way Arch Linux works and it runs smooth on my netbook (even faster than Ubuntu), I used it some time ago but at the time I wasn't using these audio tools, I'm curious about this configuration so I will give a try again and see how stuff works, my favorite KXStudio tools (even synthpod) are on AUR so I'am not going to have major problems (I think).

> sudo apt-get install libevas1-engines-x
I don't know if this would resolve my issue on ubuntu, and I'm not going to test it since my messed up and broken packages don't let me install anything and I'm migrating to another distro, but well, at least this thread will help someone someday (I think lol).

Thanks!
