### ISSUE TITLE
Midi automation cc signals of logarithmic parameters are interpreted as linear

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#30]
I'm searching for a plugin host that can be used live, supports NSM and is able to receive midi + send midi feedback to my controller when loading a new patch. Synthpod may possibly be exactly what i'm looking for.

There's only one problem. When i bind a midi control knob to a logarithmic parameter like for example frequency, the midi CC messages are interpreted linearly, so my low pass filter will jump from 10 -> 167.40. The frequency knob in the gui is behaving logarithmically.

**Comment by ventosus** [comment]
thanks for reporting.

indeed, under automation, the logarithmic flag is not considered.

needs fixing.

**Comment by Spunge** [comment]
Thanks for the fast reply. 

I would be very grateful for a fix as the plugin host is the last piece of the puzzle for my live performance setup.

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/21>
