### ISSUE TITLE
Plugin GUI problems

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#31]
Almost all plugin UI's don't show up (calf suite plugins for example).

The only UI's that work for me are distrho's EQ 3 and dragonfly hall reverb, but even those often only show a window title bar without the actual UI and show some garbled artifacts in the window managers app switcher. None of these problems give any terminal output.

Trying to launch a unsupported plugin (like the linux studio suite plugins) does give some useful output.

The synthpod documentation states that UI's are supported, am i missing something here? Is this a bug? Is there something i can do to get useful debugging output?

I'm running synthpod-git 0.1.6015-1

**Comment by ventosus** [comment]
Thanks for reporting.

> Almost all plugin UI's don't show up (calf suite plugins for example).

Those are GTK UIs. Have you built in support for those ?

By default only support for X11 and external UIs is builtl in. If you want support for GTK2/3, QT4/5, you have to enable those at compile time.

    meson -Duse-qt4=true -Duse-qt5=true -Duse-gtk2=true -Duse-gtk4=true -Duse-x11=true build

> Trying to launch a unsupported plugin (like the linux studio suite plugins) does give some useful output.

Which is is ?

**Comment by Spunge** [comment]
Ah, i just built the arch AUR package, which does not pass any flags it seems. Now i compiled with the flags you provided and i'm now looking at beautiful GUI elements, thank you!

The unsupported plugin i tried to add was LSP compressor stereo, gave me this output:
```
(DSP) [Error] _sp_app_mod_is_supported: <http://lsp-plug.in/plugins/lv2/compressor_stereo> NOT supported: mixes DSP and UI code in same binary.                                                                                                                                   
(DSP) [Error] _sp_app_mod_add: plugin is not supported                                                                                   
```

**Comment by ventosus** [comment]
Such *bad* plugin UIs are disabled by default, you can enable them with a given flag which you can find the man page:

    man synthpod_alsa | grep -B3 bad

       -b

              Enable bad plugins

       -B

              Disable bad plugins (default)

**Comment by Spunge** [comment]
Alright, good to know, i think i will first try to run only "good" plugins then ;)

Thanks again for the fast response and clear answers.
