### ISSUE TITLE
Midi cc output differs from midi cc input

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#32]
When i send some midi cc to a mapped parameter in synthpod, the midi cc synthpod passes back often differs from the input:

```
ME: knob_0 on channel 1 turned to value: 1       
SYNTHPOD: knob_0 on channel 1 turned to value: 0 
SYNTHPOD: knob_0 on channel 1 turned to value: 0 
SYNTHPOD: knob_0 on channel 1 turned to value: 0 
SYNTHPOD: knob_0 on channel 1 turned to value: 0 
ME: knob_0 on channel 1 turned to value: 2       
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
ME: knob_0 on channel 1 turned to value: 3       
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
ME: knob_0 on channel 1 turned to value: 4       
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
ME: knob_0 on channel 1 turned to value: 5       
SYNTHPOD: knob_0 on channel 1 turned to value: 4 
SYNTHPOD: knob_0 on channel 1 turned to value: 4 
SYNTHPOD: knob_0 on channel 1 turned to value: 4 
ME: knob_0 on channel 1 turned to value: 4       
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
ME: knob_0 on channel 1 turned to value: 3       
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
SYNTHPOD: knob_0 on channel 1 turned to value: 3 
ME: knob_0 on channel 1 turned to value: 2       
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
SYNTHPOD: knob_0 on channel 1 turned to value: 1 
```

Jack ouput of my out port
```
$> jack_midi_dump me
 164: b1 00 01 control change (channel  1): controller   0, value   1
 169: b1 00 02 control change (channel  1): controller   0, value   2
  18: b1 00 03 control change (channel  1): controller   0, value   3
 136: b1 00 04 control change (channel  1): controller   0, value   4
  66: b1 00 05 control change (channel  1): controller   0, value   5
 157: b1 00 04 control change (channel  1): controller   0, value   4
 159: b1 00 03 control change (channel  1): controller   0, value   3
  28: b1 00 02 control change (channel  1): controller   0, value   2
```
Jack output of synthpod out port:
```
   0: b1 00 00 control change (channel  1): controller   0, value   0
   0: b1 00 00 control change (channel  1): controller   0, value   0
   0: b1 00 00 control change (channel  1): controller   0, value   0
   0: b1 00 00 control change (channel  1): controller   0, value   0
   0: b1 00 01 control change (channel  1): controller   0, value   1
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 04 control change (channel  1): controller   0, value   4
   0: b1 00 04 control change (channel  1): controller   0, value   4
   0: b1 00 04 control change (channel  1): controller   0, value   4
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 03 control change (channel  1): controller   0, value   3
   0: b1 00 01 control change (channel  1): controller   0, value   1
   0: b1 00 01 control change (channel  1): controller   0, value   1
   0: b1 00 01 control change (channel  1): controller   0, value   1
   0: b1 00 01 control change (channel  1): controller   0, value   1
   0: b1 00 01 control change (channel  1): controller   0, value   1
   0: b1 00 01 control change (channel  1): controller   0, value   1
   0: b1 00 01 control change (channel  1): controller   0, value   1
```

Sometimes they are the same, most of the times sythpod reports the value to be 1 lower. 

I mapped the knob / channel to a parameter and selected "input" and "output".

**Comment by ventosus** [comment]
Thanks for reporting.

> Sometimes they are the same, most of the times sythpod reports the value to be 1 lower.

There are 2 things going on here:

1. ther's a hidden rounding error
2. you're comparing *signals* with differing temporal resolutions

Rounding error should be fixed in 0c080d0c347692b9750a8de16f5d3757b084170e.

You're MIDI automation input has a temporal resolution of an audio sample, e.g. MIDI events are sample-accurate. As you're automating a plugin control, which is read/written only once per period, you're MIDI automation output has a temporal resolution of an audio period, only.

If you thus send 3/4 during the sample audio period to your control, you'll only ever get a 4 out (clearly seen by the event timestamps).

> I mapped the knob / channel to a parameter and selected "input" and "output".

Why would you do that instead of using the original MIDI signal in the first place ? (just out of curiosity)

**Comment by Spunge** [comment]
Ah, i'll send the inputs without the time value then, i sent it as i expected it to maybe be used for smoothing the control changes.

> Why would you do that instead of using the original MIDI signal in the first place ? (just out of curiosity)

I save and load sessions via NSM and would like the controller knobs to reflect the current values of the plugin parameters after loading a session. (This is not working still as synthpod does not send midi state after connecting, but only when loading up the GUI elements of plugins). Plus i would like the controller knobs to reflect changes i make in GUI elements.

My aim is to be able to load up a prepared session and play around with it live, after which i can load up a different session and have the controller reflect the new loaded state. For this i need the host to push the state to the controller. When playing around with the knobs live, i need the controllers signals to be sent to the host.

**Comment by Spunge** [comment]
The midi mapping behaviour of amsynth is a good example of what i'm looking for. Amsynth does not send midi output when responding to midi input, but does send output when turning knobs in the GUI or when loading up a new patch.

**Comment by Spunge** [comment]
The floor => round patch fixed my problem and i'm now able to control plugin parameters with the GUI and my midi controller.

Now it would be nice to not have to right click each plugin to push state to the controller on loading a new session, is there an easy way to trigger synthpod to output midi cc state of all mapped parameters?

**Comment by Spunge** [comment]
Weird, i'm now trying with a new synthpod session, and that does send out midi cc state on starting it seems. I'm not sure why my first session is behaving differently. I will investigate tomorrow.

**Comment by ventosus** [comment]
> My aim is to be able to load up a prepared session and play around with it live, after which i can 
> load up a different session and have the controller reflect the new loaded state. For this i need 
> the host to push the state to the controller. When playing around with the knobs live, i need the 
> controllers signals to be sent to the host.

Sure, that makes sense. got it.

This is a handy plugin bundle for debugging any kind of event signals inside synthpod, may be of use to you while tinkering.

https://open-music-kontrollers.ch/lv2/sherlock/
https://www.archlinux.org/packages/community/x86_64/sherlock.lv2/

**Comment by Spunge** [comment]
> This is a handy plugin bundle for debugging any kind of event signals inside synthpod, may be of use to you while tinkering.
Thanks

I will close this issue as the original problem is solved.
