### ISSUE TITLE
Plugin UI windows not resizable

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#34]
I'm trying to use zyn-fusion. The interface scales very well. After discovering that i could not resize the zyn-fusion window in any plugin host, i found that it passed: http://lv2plug.in/ns/extensions/ui/#noUserResize Which i fixed locally and reported: https://github.com/zynaddsubfx/zyn-fusion-issues/issues/226

After this fix i'm able to resize the plugin window in carla, but synthpod does not seem to support the ui:noUserResize flag.

**Comment by ventosus** [comment]
thanks for reporting.

synthpod does not itself restrict plugin UI resize (I myself am disgusted by non-resizable UIs as they don't play well with my beloved tiling window manager).

synthpod simply clones X11 window size hints from plugin UI to parent embedding X11 window.

It just happens, that Zyn fusion seems to set the X11 window hints to garbage values:

* min_width: 1 px
* min_height: 1 px
* max_width: 1 px
* max_height: 1px

If min_size == max_size, for X11 this means the UI is not resizable. Carla may just ignore the UI's window size hints.

**Comment by ventosus** [comment]
there's a workaround in eca9809237d2f3b5a53f390cb3f4cb63a0b5fdf8

but this should really be fixed upstream in https://github.com/zynaddsubfx/zynaddsubfx

**Comment by Spunge** [comment]
Ah, alright, thanks for the workaround! I'll update the https://github.com/zynaddsubfx/zyn-fusion-issues/issues/226 issue with this information.

**Comment by Spunge** [comment]
The workaround is not working for me, xwininfo is telling me this:
```
  Normal window size hints:                       
      Program supplied size: 1181 by 659          
      Program supplied minimum size: 1181 by 659  
      Program supplied maximum size: 1181 by 659  
  No zoom window size hints defined               
```
about size hints

**Comment by ventosus** [comment]
After fixing #33, zyn does report valid X11 size hints.

But it reports the following:

size: 1181x659
min_size: 1181x659
max_size: 1181x659

So, it reports itself as non-resizable to X11 and synthpod honors that. I don't feel like adding a quirk to overwrite this, because it'll break all the other UIs which report sane X11 size hints.

**Comment by Spunge** [comment]
> So, it reports itself as non-resizable to X11 and synthpod honors that. I don't feel like adding a quirk to overwrite this, because it'll break all the other UIs which report sane X11 size hints.

Alright, that sounds reasonable, i'll report this to the zyn-fusion maintainer then. Thanks for checking.

**Comment by ventosus** [comment]
If you want zyn fusion to be resizable until this gets fixed upstream, you can oversteer this behaviour by commenting out the call to 'xcb_icccm_set_wm_size_hints':

https://github.com/OpenMusicKontrollers/synthpod/blob/master/bin/synthpod_sandbox_x11.c#L104
