### ISSUE TITLE
Synthpod is outputting midi cc of bound controls every JACK period

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#35]
Sometimes current midi CC values of bound controls are sent to midi output every jack period (probably, it's hard to count at the speed at which it's outputting midi signals)

I'm not sure what's causing the problem:
* It can happen for a subset of bound controls instead of all.
* It can happen for certain values of a control, but not for others (for example 45...49 is output every period, but this behaviour stops at 50 and continues at 51)
* It can happen for all controls when turning a knob after loading a session.

This is happening to me in a lot of separate cases and i'm unable to spot a pattern.

**Comment by ventosus** [comment]
Thanks for reporting.

I have seen that too, needs fixing.

**Comment by Spunge** [comment]
Output occurs when bound control is scrolled into view in the GUI. After scrolling the parameter out of view, the output is gone.

Synthpod stops accepting input from all bound controls when the problem has occurred also after disabling midi output of bound controls.

I now have a project in which in can reliably reproduce this behaviour, would that be of use?

**Comment by ventosus** [comment]
I cannot see this behaviour anymore, so guess it has been fixed in the meantine. If not, feel free to reopen.
