### ISSUE TITLE
Zyn-fusion macro slot values are not saved

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#36]
The values of macro slots of zyn-fusion are not saved. First i thought this was a problem with zyn itself, as saving zyn-fusion standalone via NSM also doesn't seem to save the macro values.

To my surprise though, the values *are* saved in carla and ardour. Any idea what's up? I have not encountered this behaviour (yet?) with other plugins.

**Comment by ventosus** [comment]
Thanks for reporting.

Well, I don't know what this macro values are in the first place.

Can you be more specific what you did with a step-wise explanation and what you expected to happen ?

**Comment by Spunge** [comment]
Ah, sorry. here's what i'm trying to do:

Zyn has 16 controls i can assign instead of midi learn for all its parameters:
![image](https://user-images.githubusercontent.com/1842108/61998600-bc388a00-b0b2-11e9-80df-81a7083ae08e.png)

I can assign parameters to a macro by enabing the learn button:
![image](https://user-images.githubusercontent.com/1842108/61998616-decaa300-b0b2-11e9-8d38-25232d442513.png)
,turning knobs in the interface, and disabling learn. All these controls are then available under slots 1 - 16

![image](https://user-images.githubusercontent.com/1842108/61998755-3407b400-b0b5-11e9-8943-d7382b611857.png)
![image](https://user-images.githubusercontent.com/1842108/61998762-50a3ec00-b0b5-11e9-8052-4f17ca90ded6.png)

Now, after some experimentation, it seems to me these values are only saved when i set them via the virtual knob in the interface, but not when i set them via midi automation, could this be?

**Comment by ventosus** [comment]
Thanks, that's crystal clear now.

I've tested you're described setup with and without NSM. The slots save and restore just fine here.

Can you test whether other plugins have the same issue ?

> Now, after some experimentation, it seems to me these values are saved when i set them via the > virtual knob in the interface, but not when i set them via midi automation, could this be?

No, Both methods change the very same variable on the underlying engine, and the very same variable is saved to disk, too.

**Comment by Spunge** [comment]
> No, Both methods change the very same variable on the underlying engine, and the very same variable is saved to disk, too.

Could it be something else which causes this behaviour? I've opened a new NSM session, only jackpatch and synthpod, with only a zyn synth, and it's showing this behaviour... It persists values set by mouse & virtual knobs across restarts, it does not persist values that i set via bound midi controls.

Until now it's only the values from zyn, i will try other plugins and report back.

**Comment by Spunge** [comment]
This is from me saving the session 4 times, the first two times i saved after turning a virtual knob, the second two times i turned the associated bound midi control knob:

```
$> cat strace.log | grep -o -P '.{0,10}slot1\\.{0,30}'
:symbol \"slot1\" ;\n\t\tpset:value 0.80303037
kSymbol \"slot1\"\n\t\t\t\t]\n\t\t\t)\n\t\t] ;
:symbol \"slot1\" ;\n\t\tpset:value 0.84848493
kSymbol \"slot1\"\n\t\t\t\t]\n\t\t\t)\n\t\t] ;
:symbol \"slot1\" ;\n\t\tpset:value 0.84848493
kSymbol \"slot1\"\n\t\t\t\t]\n\t\t\t)\n\t\t] ;
:symbol \"slot1\" ;\n\t\tpset:value 0.84848493
kSymbol \"slot1\"\n\t\t\t\t]\n\t\t\t)\n\t\t] ;
```

[strace.log](https://github.com/OpenMusicKontrollers/synthpod/files/3438558/strace.log)

**Comment by ventosus** [comment]
Ah, got it. Should be fixed in 4e7ce79573a772f8f3b06fdfcdee45629a9fe4ae.

**Comment by Spunge** [comment]
Problem is gone! Your response times are impressive :)

Thanks!

**Comment by ventosus** [comment]
> Problem is gone! Your response times are impressive :)

Just don't expect it to be always like that...
