### ISSUE TITLE
Synthpod interface settings panel CPU usage

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#37]
When i open the synthpod interface, the sandbox thread will use around ~12% CPU. Whenever i open the "Settings" panel in the synthpod interface, the CPU usage will jump to 100% and cause a lot of jack xruns.

When i close the settings panel again, cpu usage will return to the more sane ~12%.

**Comment by ventosus** [comment]
Thanks for reporting.

This is a known problem. The used nuklear toolkit is nice but quite inefficient when one wants to draw *really* long scrollable lists (read: presets, plugins), e.g. what you have in the settings.

As the toolkit will soon*ish* be deprecated in favor of a new one [1], I won't invest any time to fix this, sorry.

[1] https://git.open-music-kontrollers.ch/lad/d2tk/about/

**Comment by ventosus** [comment]
A workaround for now may be to always put something into the preset filter entry in order to reduce the preset list.

**Comment by ventosus** [comment]
d25750f8fb6513255adeb91fc5b4b31b9c0cc398 skips the logic to asoociate presets with their bank and should ameliorate the issue quiet a bit until the new UI will be ready.

**Comment by Spunge** [comment]
> As the toolkit will soonish be deprecated in favor of a new one [1], I won't invest any time currently to fix this, sorry.

Very understandable, thanks for the hotfix :)

One minor thing though, not that it really botters me, but the new version calls itself "synthpod-jack" instead of "synthpod".
![image](https://user-images.githubusercontent.com/1842108/62012330-44875f80-b185-11e9-951d-dbc9dc3b17ee.png)
When loading up existing sessions it will not load saved data as NSM will name the config directory after the software:
```
-rw-r--r--  1 johan johan    0 Jul 28 22:11 JACKPatch.nPQCM.jackpatch
-rwxr-xr-x  1 johan johan    0 Jul 28 22:11 .lock
-rw-r--r--  1 johan johan   60 Jul 28 22:11 session.nsm
drwxr-xr-x  4 johan johan 4.0K Jul 28 22:11 Synthpod-JACK.nTFMU
drwxr-xr-x 16 johan johan 4.0K Jul 28 00:51 Synthpod.nTFMU

~/NSM Sessions/02_setup $> rm -rf Synthpod-JACK.nTFMU 
~/NSM Sessions/02_setup $> mv Synthpod.nTFMU Synthpod-JACK.nTFMU
```
After moving things around the data loads fine and the hotfix is working.

I must say the new UI looks very promising. I'm really liking that new flowmatrix. Keep up the great work!

**Comment by Spunge** [comment]
Woah, that NSM switch mode logic is working beautifully though.

**Comment by ventosus** [comment]
> One minor thing though, not that it really botters me, but the new version calls itself "synthpod-jack" > instead of "synthpod".

Ah, yes, sorry. Renaming of NSM client name was needed so that synthpod-alsa, synthpod-jack and synthpod-dummy can coexist in the same NSM session for this:

> Woah, that NSM switch mode logic is working beautifully though.

to work properly.
