### ISSUE TITLE
build fails: undefined reference to `ELM_SCALE_SIZE'

### ISSUE THREAD

**Issue by rghvdberg** [OpenMusicKontrollers/synthpod#4]
```
[ 41%] Linking C shared library libsynthpod_ui.so
CMakeFiles/synthpod_ui.lib.dir/synthpod_ui_modlist.c.o: In function `_modlist_content_get':
synthpod_ui_modlist.c:(.text+0x1431): undefined reference to `ELM_SCALE_SIZE'
synthpod_ui_modlist.c:(.text+0x1442): undefined reference to `ELM_SCALE_SIZE'
collect2: error: ld returned 1 exit status
ui/CMakeFiles/synthpod_ui.lib.dir/build.make:744: recipe for target 'ui/libsynthpod_ui.so.0' failed
make[2]: *** [ui/libsynthpod_ui.so.0] Error 1
CMakeFiles/Makefile2:140: recipe for target 'ui/CMakeFiles/synthpod_ui.lib.dir/all' failed
make[1]: *** [ui/CMakeFiles/synthpod_ui.lib.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

what am I doing wrong?

**Comment by ventosus** [comment]
> what am I doing wrong?
nothing! besides using an outdated libelementary :-)

ELM_SCALE_SIZE is available since 1.12 only.

I've added a preprocessor fix for this in 9a9adf58868ac2b469f2f8f9e8a72e47a38406a7

**Comment by rghvdberg** [comment]
it builds :+1: 
also had to install `libevas1-engines-x`
and had to run `sudo ldconfig /usr/local/lib`

**Comment by ventosus** [comment]
> also had to install libevas1-engines-x

yes, debianesque distributions list the X11 engines as an optional dependency only.

> and had to run sudo ldconfig /usr/local/lib

yes, synthpod DSP and UI are installed as libraries and library cache thus needs to be updated after the first installation.

this information would probably fit well into the README...
