### ISSUE TITLE
Plugin GUI not loading state

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#40]
When i'm using wolf shaper and create a waveshaping function:

![image](https://user-images.githubusercontent.com/1842108/62013054-165a4d80-b18e-11e9-85bc-99b687f02130.png)

I can't see it after closing and opening the x11 plugin GUI:

![image](https://user-images.githubusercontent.com/1842108/62013078-4efa2700-b18e-11e9-829f-f2e993b161a3.png)

The function is still there though, shaping the waves.

**Comment by ventosus** [comment]
I doubt that this will work in any other host out there.

The curve is transported via an LV2 atom port, but the plugin's manifest does nowhere tell, that the UI wants to receive events from that port. As the port has a *very* weird configuration, syntpod does not automatically subscribe to the port's events.

    lv2:port [
        a lv2:InputPort, atom:AtomPort ;
        lv2:index 4 ;
        lv2:name "Events Input" ;
        lv2:symbol "lv2_events_in" ;
        rsz:minimumSize 2048 ;
        atom:bufferType atom:Sequence ;
        atom:supports <http://lv2plug.in/ns/ext/atom#String> ;
    ] ;

**Comment by Spunge** [comment]
This is working in ardour & carla, also across host restarts.

Thanks for looking into this, i'll take this up with the maintainer of wolf-shaper.

**Comment by pdesaulniers** [comment]
@falkTX Does that look like a bug in DPF's ttl generation?

Furthermore, if I add many vertices to the graph, some errors start appearing in the console output:
```
(DSP) [Trace] _notification_list_add: failed to append
(DSP) [Trace] _schedule_work: failed to request buffer
(DSP) [Trace] _schedule_work: failed to request buffer
```

**Comment by ventosus** [comment]
> DSP) [Trace] _notification_list_add: failed to append

This means that your input atom port (which is defined as 2048 bytes) is too short for the event you want to add from ui->dsp.

**Comment by ventosus** [comment]
> (DSP) [Trace] _schedule_work: failed to request buffer

This means that the work ringbuffer (which is fixed to 2018 bytes) is too short for your work load. How big is your work load, just out of curiosity ?
