### ISSUE TITLE
Opening zyn-fusion gui results in black window

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#43]
Opening the zyn-fusion GUI via synthpod now results in a black window, the window does have the correct width & height though.

![image](https://user-images.githubusercontent.com/1842108/64201319-b773ac80-ce8e-11e9-8d49-810f19bd2dd9.png)

**Comment by ventosus** [comment]
Iv'e had this, too recently with zyn-fusion in *every* host.

Have you checked in other hosts before reporting here ?

Most probably some graphics related changes in Arch. Needs a rebuild of zyn-fusion.

**Comment by Spunge** [comment]
> Have you checked in other hosts before reporting here ?

Yeah i checked with carla, which is working fine.

> Most probably some graphics related changes in Arch. Needs a rebuild of zyn-fusion.

I've updated everything, just built latest fusion & synthpod, still no interface :(

**Comment by Spunge** [comment]
Yes, thank you very much :)
