### ISSUE TITLE
synthpod_jack not starting with realtime priorities

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#44]
synthpod_jack runs at nice level 20 while synthpod_alsa runs at nice level -61.

**Comment by ventosus** [comment]
synthpod_alsa sets realtime priorites to values given on command line (see manpage).

synthpod_jack inherits realtime priorities from JACK itself via jack_client_real_time_priority [1]. So its seems that JACK itself is not run with realtime priorities in the first place.

[1] http://jackaudio.org/files/docs/html/group__ClientThreads.html#ga4ee2fcbb266618d66a2cf354d8c54359

**Comment by Spunge** [comment]
Ah yeah, seems arch jack2 update broke my things. Thanks for the pionter.
