### ISSUE TITLE
Rename the "X11" button to "Show plug-in GUI"

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/synthpod#45]
I think renaming "X11" would make the interface much more intuitive - I've been looking for this fro a long time before I realized that's the button I need to open the plug-ins GUI.

There's plenty of room on that button for more text:
![Screenshot_20190906_000338](https://user-images.githubusercontent.com/491704/64386569-c9de1980-d039-11e9-8c5f-9ac93492c8cc.png)

What do you think?

**Comment by ventosus** [comment]
Plugins can have multiple UIs (so the shorter the better). Putting the widget type on the button is an easy way to discriminate between them. Ideally, developers would put a short description and/or comment on their UIs that could be shown here, but nobody does that. Putting the UI's URI is just too cumbersome and long...

In the special case with only one available UI, your proposal makes sense, though, the user should not care what kind of UI she's opening, as there's only a single one.

![2019-09-06-095659_198x40_scrot](https://user-images.githubusercontent.com/1863184/64411279-24549580-d08d-11e9-8c9e-b38fb11c9bdd.png)

**Comment by ventosus** [comment]
fixed in b4753d158c5741847d44780d7fd777f01456da3d

**Comment by unfa** [comment]
Interesting. I didn't know plugins can expose multiple GUIs...

Thank you!

**Comment by ventosus** [comment]
> Interesting. I didn't know plugins can expose multiple GUIs...

Most people don't know, because the most prominent LV2 host (Ardour) does still not support it, iirc.
