### ISSUE TITLE
Synthpod GUI launches when opening NSM project

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#47]
Is there a way i can prevent starting synthpod_ui processes when opening a NSM session? I'm running ~20 synthpods in my average session (16 instruments & at least 4 busses), and having to close 20 GUI's every time i open a session quickly gets boring.

**Comment by ventosus** [comment]
How unfortunate, indeed.

I had the impression that the NSM daemon would remember visibility state, but apparently that's not the case [1].

Can be fixed...

[1] http://non.tuxfamily.org/nsm/API.html#n:1.2.4.1.

**Comment by ventosus** [comment]
fixed in 7452282d077a0ca685bee07b9f1a967d5b35bdaa

**Comment by ventosus** [comment]
already existing projects will have visibility turned off at next time opening, as they don't have the visibility state set yet in the project save state.
