### ISSUE TITLE
Synthpod not reporting jack BPM to plugins

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#48]
Some plugins (calf vintage delay for example) give you the option to sync delay to host BPM. It seems Synthpod is not reporting this to plugins, as they will always show 120 BPM.

I've tested with Carla & Ardour to confirm, these both do report host BPM to plugins.

**Comment by ventosus** [comment]
The proper way for a plugin to get a BPM value is to implement the time extension [1], imho.

The vintage delay seems to want to get BPM via a control port by a designation hint [2]. The support for such designations is optional for hosts.

Carla & Ardour have a single global time transport scheme (e.g. they support only one single transport for all plugins in the graph), so they can easily support a BPM port designation for all plugins.

In Synthpod, time is just another atom event stream, and a single plugin graph can have an arbitrary number of time transport schemes. It thus makes no sense for Synthpod to support that. Better to fix the plugin to support the time extension.

[1] http://lv2plug.in/ns/ext/time/
[2] http://lv2plug.in/ns/lv2core/#designation

**Comment by Spunge** [comment]
Thanks for the explanation, i will report this to the calf maintainer.

**Comment by falkTX** [comment]
that is quite big to requests for plugins to implement atom port + urid-map + time parsing for something that can easily just have as a control port.
for plugins that already have an atom port, that is quite fine, but I think that is asking too much from plugin authors that are only interested in a single value, specially since all other hosts already provide this value

does it make sense to send multiple time events to a plugin atom port? If not, I dont really see the reason synthpod cant just provide this information. instead of taking it from a global place, take it from whatever previous plugin or source provides the time, and set the designation.

**Comment by ventosus** [comment]
> for plugins that already have an atom port, that is quite fine

Which is exactly the case here.

> but I think that is asking too much from plugin authors that are only interested in a single value, 
> specially since all other hosts already provide this value.

s/all/all but jalv/

> does it make sense to send multiple time events to a plugin atom port?

No, but that's not what I meant. It's valid to have different transports running in the same graph, e.g. I often have 3 transports running (1x, 2x, 4x) for different subpatches in the same graph.

> If not, I dont really see the reason synthpod cant just provide this information. instead of taking it
> from a global place, take it from whatever previous plugin or source provides the time, and set the 
> designation.

I've never said that this is impossible (or hard) todo. There's no technical reason against it at all.

As Synthpod has no notion of time at all inside the plugin graph, it just makes no sense to add a lot of code just for a handful of plugins (which I never use) that want that optional feature. It's as simple as that.

**Comment by ventosus** [comment]
For the time being, this can be solved via automations, I've added orbit#monitor plugin which breaks transport information out to parameters.

https://github.com/OpenMusicKontrollers/orbit.lv2/commit/5517c496a7a540a5cf170af3c957e1bb9a0247b2

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/20>
