### ISSUE TITLE
can't delete system sink/source

### ISSUE THREAD

**Issue by PrinzNika** [OpenMusicKontrollers/synthpod#51]
It is possible to create new system sink/source plugins but you can't delete them with 'x'

**Comment by ventosus** [comment]
Thanks for reporting in.

Congratulations, you've found a bug.

That you cannot delete them, is intended and thus correct.

It should not be possible to create more than 1 main sink/source plugins in the first place, e.g. those plugins should not be available to the user in the first place.

If you want additional audio/MIDI sink/sources, use the proper plugins:

    Synthpod Audio Source/Sink
    Synthpod CV Source/Sink
    Synthpod MIDI Source/Sink
    Synthpod OSC Source/Sink

**Comment by ventosus** [comment]
fixed in 9d5f007a65dfbdb45d95a745476a55be215f051b

**Comment by PrinzNika** [comment]
awesome, is it possible to rename the ports from within synthpod?

**Comment by PrinzNika** [comment]
if not i would create a feature request for this as it makes it much more easy to create connections to other applications

**Comment by ventosus** [comment]
> awesome, is it possible to rename the ports from within synthpod?

no

**Comment by PrinzNika** [comment]
would it be possible for synthpod to automatically name them in the order they were created? that way when simply routing a signal through it, I wouldnt have to create the audio sinks/sources  1 by 1. also my patchbay wouldnt get 'messy' like this.
![2020-03-24-212927_1920x1080_scrot](https://user-images.githubusercontent.com/48157844/77474212-06773400-6e17-11ea-871b-e5e4ecafc298.png)
![2020-03-24-212937_1920x1080_scrot](https://user-images.githubusercontent.com/48157844/77474215-07a86100-6e17-11ea-919a-89707481bb00.png)

**Comment by ventosus** [comment]
> would it be possible for synthpod to automatically name them in the order they were created?

This information is not stored anywhere, yet, but theoretically possible.

Regarding port naming: Would you need every single port to be renamable, or would it be enough, if one could rename the source/sink plugin as a whole, e.g:

    Reverb 1
    Reverb 2
    Reverb 3
    Reverb 4

instead of:

    #2179 - Audio Sink 1
    #2179 - Audio Sink 2
    #2179 - Audio Sink 3
    #2179 - Audio Sink 4

Plugins inside synthpod can already be given an alias. One could export that to JACK port pretty names.

**Comment by ventosus** [comment]
starting from 0de7d14130fc243f8849c8747babf95e79619110, JACK ports are ordered according to system plugin creation order.

A first step into the right direction.

You seem to use QJackCtl as your patchbay. For this to work, you'll need to enable "Ordering by Index".

**Comment by PrinzNika** [comment]
wow thats a fast implementation! thank you also for the hint. I was using qjackctl for the possibility to persistently set up connections in the patchbay. 
but im currently debating switching to patchmatrix and non session management(adding jacpatch client). Have to do some further testing though as my jack server froze a few times yesterday while using it, though im not sure if non was the cause.

**Comment by PrinzNika** [comment]
oh and regarding your questing: it would of course be enough to rename the sink plugin as a whole

**Comment by ventosus** [comment]
> oh and regarding your questing: it would of course be enough to rename the sink plugin as a whole

great, this could easily be done.

**Comment by ventosus** [comment]
starting from 59f4e48b5ff32b7466b719eb502fe9bf9576df19, plugin alias names are applied to JACK port pretty names

Please test ...

**Comment by PrinzNika** [comment]
i just rebuilt synthpod following the readme instructions but im not really noticing a change. do i have to pass some specific parameter to get 59f4e48? (just starting getting familiar with git)

**Comment by ventosus** [comment]
Have you set an alias for the system port plugins ?

There's a text field in the plugin's (right) control tab.

**Comment by PrinzNika** [comment]
![2020-03-25-150851_1920x1080_scrot](https://user-images.githubusercontent.com/48157844/77545287-81d5f580-6eaa-11ea-864b-5c3eb15e76cc.png)

**Comment by ventosus** [comment]
You need a patchbay with support for JACK metadata port PRETTY_NAMES.

Don't know whether carla supports that. Recent QJackCtl does (and also port ordering).

**Comment by PrinzNika** [comment]
aha, in qjackctl it does work!
![2020-03-25-154129_1920x1080_scrot](https://user-images.githubusercontent.com/48157844/77548636-180c1a80-6eaf-11ea-9dd0-0c5618a814ec.png)

**Comment by ventosus** [comment]
answer via IRC

> 25-03 16:25 - falktx: ventosus: it does not
