### ISSUE TITLE
Feature Request: Save/Load Dialog

### ISSUE THREAD

**Issue by PrinzNika** [OpenMusicKontrollers/synthpod#52]
When hitting the save button, synthpod saves the canvas as the default preset. It would be nice to have a dialog that lets you name the preset folder. 
And also a load dialog that lets you load a previously saved preset.

**Comment by ventosus** [comment]
This will not happen soon (or ever).

I start synthpod from the command line exclusively, where you can give the load/save explicitely.

You can put synthpod under NON session management [1], though, which will give you exactly what you want.

[1] http://non.tuxfamily.org/wiki/Non%20Session%20Manager

**Comment by PrinzNika** [comment]
i havent looked into non session management yet but with a growing list of applications im using, it is about time to wrap my head around it. 

Would you mind elaborating on how you load/save from command line?

**Comment by ventosus** [comment]
There should be man pages explaining all the flags you can use.

    man synthpod_alsa
    man synthpod_jack


It's pretty straightforward, just give the directory (relative or absolute) you want to load from or save to.

    synthpod_alsa /home/user/my_awesome_audio_projects/synthpod_example_1.lv2.preset

If the preset already exists, it is loaded, if it does not yet exist, it is created. Whenever you hit save, it'll be saved to that directory.

**Comment by PrinzNika** [comment]
great, also i just tried it with NSM but i failed to save the state of synthpod.
I added the client to the session and it successfully opens and closes but for non of the save signals (SIGUSR1, SIGUSR2, SIGINT), it saves the added plugins. Only when I save in Synthpod itself, it alters the default preset. any hints?

**Comment by PrinzNika** [comment]
nevermind, got it running. it was my fault as i set it as a command line program with NSM Proxy

**Comment by ventosus** [comment]
yep, it has proper support for NSM :-)
