### ISSUE TITLE
connection matrix stuck when moving through screen edge

### ISSUE THREAD

**Issue by PrinzNika** [OpenMusicKontrollers/synthpod#53]
I have this weird error where i cant move a connection matrix when it hits the border of the visible screen. i cant select it or move it anymore. 
when it hits the edge of the collapsible settings section and i remove that section, the node gets unstuck. that isnt possible when it hits the usual graph-edge

**Comment by PrinzNika** [comment]
![out](https://user-images.githubusercontent.com/48157844/77429807-7ddaa280-6dda-11ea-997c-141960cd8610.gif)

**Comment by PrinzNika** [comment]
it wasnt like this before though, i think i had a crash of some sort

**Comment by ventosus** [comment]
This is a known issue.

Just move the whole canvas (middle mouse button + mouse move) until the edge is in the viewport in its whole again.

**Comment by PrinzNika** [comment]
ah thanks, i am using a thinkpad laptop and using the middle mouse button here doesn't move the canvas (same issues in blender) but i just tried it with a mouse and it works

**Comment by ventosus** [comment]
You most probably have an emulated scroll whell with (middle button + trackpoint) [1].

[1] https://www.thinkwiki.org/wiki/How_to_configure_the_TrackPoint#Scrolling.
