### ISSUE TITLE
Does SynthPod allow creating custom control panels?

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/synthpod#56]
I've recently done a live performance using Carla as a base.

One thing I'm missing is a way to aggregate my controls and build a custom control panel where I can see all my assigned MIDI CC controls and monitor their values.

I wonder if SynthPod can do this kind of thing?

My performance with Carla:
https://www.youtube.com/watch?v=WFBdUhHXAXk&t=2192s

**Comment by ventosus** [comment]
hi

I'm not sure whether I understand correctly (sorry I've not yet watched the video).

You'd like to have a view of all the automated controls of all the plugins together?

Like in a grid or list?

Currently there's no such view, but all the required information is already in the UI, so such a view could be added (and would find it really handy, indeed).

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/19#event-78>
