### ISSUE TITLE
Build dependencies missing on Raspberry Pi 4

### ISSUE THREAD

**Issue by okyeron** [OpenMusicKontrollers/synthpod#59]
Attempting to build Synthpod today I ran into a number of dependencies that were required for compilation (while the instructions note that some of these are optional)

`sudo apt-get install meson libglu1-mesa-dev libglew-dev libvterm-dev liblilv-dev libzita-alsa-pcmi-dev libjack-dev libxcb-icccm4-dev libxcb-xrm-dev`

I'd also previously installed `lv2-dev libsndfile1-dev libx11-dev libcairo2-dev jackd2 libudev-dev libevdev-dev liblo-dev  libasound2-dev`

This is on a Pi4 with RasPi OS/Debian 5.10.63-v7l+

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/17#event-69>
