### ISSUE TITLE
Question about  `NOT supported: mixes DSP and UI code in same binary`

### ISSUE THREAD

**Issue by rghvdberg** [OpenMusicKontrollers/synthpod#6]
`NOT supported: mixes DSP and UI code in same binary`

Will plug-ins with mixed DSP and UI code ever be supported?
Most plug-ins I use are in that catagory.

**Comment by ventosus** [comment]
Yes, everything JUCE-based mixes DSP and UI code...

You override that behaviour with the corresponding command-line switch.

    >> man synthpod_jack

    ....
    -b
        Enable bad plugins
