### ISSUE TITLE
LV2_Atom_Tuple has no member named size

### ISSUE THREAD

**Issue by cmt227** [OpenMusicKontrollers/synthpod#7]
Hi, I'm trying to build synthpod_alsa on a Raspberry Pi 3, and am getting the following build error:

`[ 50%] Building C object bin/CMakeFiles/synthpod.alsa.dir/synthpod_nsm.c.o
In file included from /home/pi/builds/synthpod/osc.lv2/osc.lv2/util.h:28:0,
                 from /home/pi/builds/synthpod/osc.lv2/osc.lv2/writer.h:25,
                 from /home/pi/builds/synthpod/bin/synthpod_nsm.c:27:
/home/pi/builds/synthpod/osc.lv2/osc.lv2/util.h: In function âlv2_osc_body_unrollâ:
/home/pi/builds/synthpod/osc.lv2/osc.lv2/util.h:437:3: error: âLV2_Atom_Tupleâ has no member named âsizeâ
   LV2_ATOM_TUPLE_FOREACH(items, atom)
   ^
/home/pi/builds/synthpod/osc.lv2/osc.lv2/writer.h: In function âlv2_osc_writer_packetâ:
/home/pi/builds/synthpod/osc.lv2/osc.lv2/writer.h:432:3: error: âLV2_Atom_Tupleâ has no member named âsizeâ
   LV2_ATOM_TUPLE_FOREACH(items, atom)
   ^
/home/pi/builds/synthpod/osc.lv2/osc.lv2/writer.h:459:4: error: âLV2_Atom_Tupleâ has no member named âsizeâ
    LV2_ATOM_TUPLE_FOREACH(arguments, atom)
    ^
/home/pi/builds/synthpod/osc.lv2/osc.lv2/writer.h:467:4: error: âLV2_Atom_Tupleâ has no member named âsizeâ
    LV2_ATOM_TUPLE_FOREACH(arguments, atom)
    ^
bin/CMakeFiles/synthpod.alsa.dir/build.make:100: recipe for target 'bin/CMakeFiles/synthpod.alsa.dir/synthpod_nsm.c.o' failed
make[2]: *** [bin/CMakeFiles/synthpod.alsa.dir/synthpod_nsm.c.o] Error 1
CMakeFiles/Makefile2:254: recipe for target 'bin/CMakeFiles/synthpod.alsa.dir/all' failed
make[1]: *** [bin/CMakeFiles/synthpod.alsa.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2`

I saw an issue similar to this that you solved; it was apparently a bug in LV2 version 1.10. Can you help me out with this one? Thanks!

**Comment by ventosus** [comment]
good catch, thanks for reporting, a bug in LV2 < 1.12, indeed

fixed in 81189de710103f1479a45460a54fadba356f9ca4

**Comment by cmt227** [comment]
You're welcome! It compiles now, thanks for the fix.
