### ISSUE TITLE
ECORE error

### ISSUE THREAD

**Issue by cmt227** [OpenMusicKontrollers/synthpod#8]
Hello again! After compiling and installing I'm getting this error..

`pi@raspberrypi:~ $ synthpod_alsa
ERR<9201>:elementary elm_config.c:2520 _elm_config_sub_init() Cannot connect to X11 display. check $DISPLAY variable
Synthpod 0.1.1701
Copyright (c) 2015-2016 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under GNU General Public License 3 by Open Music Kontrollers
CRI<9201>:elementary elm_win.c:2858 _win_constructor() Software X11 engine creation failed. Trying default.
ERR<9201>:elementary elm_win.c:2994 _win_constructor() Cannot create window.
ERR<9201>:eo lib/eo/eo.c:1217 eo_error_set_internal() Error with obj '0x1479b40' at elm_win.c:2995
ERR<9201>:eo lib/eo/eo.c:1107 eo_add_internal() in elm_win.c:2718, Object of class 'Elm_Win' - One of the object constructors have failed.
ERR<9201>:eo lib/eo/eo_ptr_indirection.x:275 _eo_obj_pointer_get() obj_id (nil) is not pointing to a valid object. Maybe it has already been freed.
Error opening file /home/pi/.lv2/Synthpod_default.preset.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/pi/.lv2/Synthpod_default.preset.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/pi/.lv2/Synthpod_default.preset.lv2/manifest.ttl
playback :
  nchan  : 2
  fsamp  : 48000
  fsize  : 1024
  nfrag  : 3
  format : S16_LE
capture  : not enabled
ERR<9201>:eldbus lib/eldbus/eldbus_core.c:1003 _connection_get() Error connecting to bus of type 1. error name: org.freedesktop.DBus.Error.NotSupported error message: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
ERR<9201>: lib/eldbus/eldbus_core.c:1065 eldbus_connection_get() safety check failed: conn == NULL
Error opening file /home/pi/.lv2/Synthpod_default.preset.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/pi/.lv2/Synthpod_default.preset.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/pi/.lv2/Synthpod_default.preset.lv2/manifest.ttl
pthread_setschedparam error
pthread_setschedparam error
pthread_setschedparam error
pthread_setschedparam error
pthread_setschedparam error
ERR<9201>:ecore lib/ecore/ecore.c:733 _ecore_magic_fail() 
*** ECORE ERROR: Ecore Magic Check Failed!!!
*** IN FUNCTION: ecore_con_server_send()
ERR<9201>:ecore lib/ecore/ecore.c:735 _ecore_magic_fail()   Input handle pointer is NULL!
ERR<9201>:ecore lib/ecore/ecore.c:746 _ecore_magic_fail() *** NAUGHTY PROGRAMMER!!!
*** SPANK SPANK SPANK!!!
*** Now go fix your code. Tut tut tut!`

Any insight? Thanks.

**Comment by ventosus** [comment]
You don't have any Xserver running. Synthpod by default starts with its UI enabled (and without any Xserver obviously fails), you thus need to disable it at startup, there's a command line switch for that.

    man synthpod_alsa

     -G
        Disable GUI
